name = "SurvivalDistributions"
uuid = "7121986e-ae89-4673-ae4e-1cb822919a18"
authors = ["Oskar Laverny <oskar.laverny@univ-amu.fr> and contributors"]
version = "1.0.0-DEV"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[compat]
Distributions = "0.25"
Test = "1.6"
TestItemRunner = "0.2"
julia = "1.6.7"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Aqua", "Test", "TestItemRunner"]